[package]
name = "lunk"
version = "0.1.0"
edition = "2021"
license = "ISC"
description = "Event graph processing"
repository = "https://github.com/andrewbaxter/lunk"
readme = "readme.md"

[dependencies]
gensym = "0.1.0"
paste = "1.0.14"
