[package]
name = "lunk"
version = "0.3.2"
edition = "2021"
license = "ISC"
description = "Event graph processing"
repository = "https://github.com/andrewbaxter/lunk"
readme = "readme.md"

[dependencies]
paste = "1.0.14"
